openapi: 3.1.0
info:
  title: Customer API
  version: 1.0.0
  description: |
    **DEPRECATED**: This API version is deprecated. Please use v2.
    Shutdown date: 2024-12-31
servers:
  - url: https://api.example.com/v1/customer-api
paths:
  /customers:
    get:
      summary: List customers (DEPRECATED)
      deprecated: true
      responses:
        "200":
          description: List of customers
